name: intolera
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  get_it: ^2.0.1
  data_connection_checker: ^0.3.4
  flutter_bloc: ^0.21.0
  font_awesome_flutter: ^8.4.0
  image_picker: 0.6.1+4
  equatable: ^0.4.0
  shared_preferences: ^0.5.3+4
  http: ^0.12.0+2
  dartz: ^0.8.6
  firebase_ml_vision:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0

flutter:
  uses-material-design: true

  assets:
   - assets/logos/facebook.jpg
   - assets/logos/google.jpg
   - assets/icons/barcode-scan.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
