name: intolera
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  image_picker: 0.6.1+4
  equatable: ^0.4.0
  dartz: ^0.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0

flutter:
  uses-material-design: true

  assets:
   - assets/logos/facebook.jpg
   - assets/logos/google.jpg
   - assets/icons/barcode-scan.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
